from . import ce_instance
from . import ce_sale_workflow_config
from . import ce_product_brand
from . import ce_product_product
from . import ce_product_template
from . import ce_sale_order
from . import ce_sale_order_line
from . import ce_log_book
from . import res_partner
from . import channel_payment_options
from . import ce_name
from . import ce_stock_picking
from . import ce_product_images
from . import ir_http
from . import translation
